-- Asistencia de PRUEBA (generada por generar_inscritos.py). Ejecutar en Supabase → SQL Editor
-- después de importar inscritos_prueba_cartagena.csv. 59 de 71 llegan; IERB no llega.
update public.participants set attended_at = null where email like '%@correo.test';
update public.participants p set attended_at = (date '2026-09-29' + v.hora::time) at time zone 'America/Bogota'
from (values
  ('samuel.salgado@correo.test', '08:05'),
  ('miguel.caraballo@correo.test', '07:07'),
  ('daniela.villalba@correo.test', '07:53'),
  ('daniela.rodriguez@correo.test', '08:23'),
  ('mateo.mendoza@correo.test', '07:34'),
  ('sara.castro@correo.test', '08:15'),
  ('jesus.cabarcas@correo.test', '07:31'),
  ('luis.villalba@correo.test', '07:19'),
  ('nicolas.jimenez@correo.test', '08:39'),
  ('ana.arrieta@correo.test', '08:22'),
  ('sofia.buelvas@correo.test', '07:59'),
  ('isabella.padilla@correo.test', '08:28'),
  ('natalia.julio@correo.test', '07:38'),
  ('tomas.ortega@correo.test', '07:04'),
  ('paula.ortega@correo.test', '07:33'),
  ('kevin.castro@correo.test', '07:49'),
  ('camila.herrera@correo.test', '07:35'),
  ('esteban.pajaro@correo.test', '07:36'),
  ('valentina.ortega@correo.test', '07:52'),
  ('juan.padilla@correo.test', '07:47'),
  ('juan.perez@correo.test', '08:13'),
  ('alejandro.diaz@correo.test', '07:29'),
  ('salome.guerrero@correo.test', '07:44'),
  ('salome.barrios@correo.test', '07:49'),
  ('laura.blanco@correo.test', '07:43'),
  ('jesus.mendoza@correo.test', '07:28'),
  ('yuliana.marrugo@correo.test', '07:10'),
  ('luis.julio@correo.test', '07:12'),
  ('sara.torres@correo.test', '08:18'),
  ('jesus.salgado@correo.test', '08:35'),
  ('jesus.zuniga@correo.test', '07:46'),
  ('paula.orozco@correo.test', '07:00'),
  ('natalia.cabarcas@correo.test', '08:22'),
  ('natalia.jimenez@correo.test', '08:41'),
  ('andres.salgado@correo.test', '08:28'),
  ('alejandro.jimenez@correo.test', '07:28'),
  ('luciana.ortega@correo.test', '07:57'),
  ('jesus.orozco@correo.test', '07:18'),
  ('andres.blanco@correo.test', '07:49'),
  ('alejandro.morales@correo.test', '07:36'),
  ('samuel.julio@correo.test', '07:18'),
  ('kevin.castro2@correo.test', '07:33'),
  ('sebastian.buelvas@correo.test', '08:32'),
  ('carlos.villalba@correo.test', '08:31'),
  ('mariana.gomez@correo.test', '07:00'),
  ('mateo.morales@correo.test', '08:00'),
  ('natalia.ortega@correo.test', '07:43'),
  ('andres.marrugo@correo.test', '07:45'),
  ('nicolas.mendoza@correo.test', '07:58'),
  ('tomas.zuniga@correo.test', '07:36'),
  ('andres.barrios@correo.test', '07:13'),
  ('laura.castro@correo.test', '07:41'),
  ('samuel.barrios@correo.test', '07:27'),
  ('gabriela.caraballo@correo.test', '07:05'),
  ('juan.torres@correo.test', '08:11'),
  ('laura.morales@correo.test', '08:02'),
  ('carlos.herrera@correo.test', '08:36'),
  ('gabriela.barrios@correo.test', '08:20'),
  ('andres.mendoza@correo.test', '07:23')
) as v(email, hora)
where p.email = v.email;
